### ISSUE TITLE
checkHDUs params not loaded

### ISSUE THREAD

**Issue by felipeaoli** [desihub/qlf#143]
Using the function get_scalar_metrics(selected_process_id, cam), 'checkHDUs' is not appearing among the keys of the loaded dictionary. 
This field 'params' inside this dictionary is now necessary to read the exposure time.

**Comment by felipelm** [comment]
@felipeaoli is this still happening?

**Comment by felipeaoli** [comment]
This is no longer necessary since we have moved to mergedQA. I'm closing this issue now.
