### ISSUE TITLE
Why does QLF use a GPL license?

### ISSUE THREAD

**Issue by weaverba137** [desihub/qlf#19]
The majority of DESI packages use a BSD-3-clause license.  If QLF contains some GPL code, then that should be explicitly documented (maybe it already is).  Or if there are other very good reasons for using it, that should be documented as well.

**Comment by sbailey** [comment]
For context, LBL and the University of California have some restrictions on employees contributing to GPL code, and it would be nice if we could keep the LBL lawyers out of this.  QLF is primarily a Brazilian contribution, but we may occasionally have non-Brazillian contributions and a BSD license would help with that.  So could we switch QLF to use 3-clause BSD, or does it have to be GPL for other reasons?

**Comment by ricardogando** [comment]
Hi, I am investigating the history behind this choice.
What I can tell is that we have documented the following dependencies and respective licenses:

- Django BSD https://www.djangoproject.com/foundation/faq/
- Speclite BSD https://github.com/dkirkby/speclite
- Fitsio GPL https://pypi.python.org/pypi/fitsio/
- Furl Unlicensed https://pypi.python.org/pypi/furl
- Pyro4 MIT https://pypi.python.org/pypi/Pyro4

These are not necessarily direct QLF dependencies.
For instance, I could only find GPL fitsio in a desiutil dependence file.

`/py/desiutil/depend.py:  'requests', 'fitsio', 'h5py', 'mpi4py', 'psycopg2', 'healpy',`

but nowhere else. 

I think it would be safe to remove this dependence from QLF and change the license.
What about the MIT one? Any conflict?

Thanks,
Ricardo

**Comment by weaverba137** [comment]
The DESI Data team's standard recommendation is BSD-3-clause.  Is there a particular preference for MIT?

Normally, you do not need to consider the licenses of the other required packages unless code from a particular package is bundled and redistributed with qlf itself.  For example, if you copied `fitsio` code into `qlf/fitsio/...`, then you would need to think about license compatibility.

**Comment by ricardogando** [comment]
Hi Ben, I updated the license to BSD-3-clause.
