### ISSUE TITLE
 qlf and flavour check

### ISSUE THREAD

**Issue by Srheft** [desihub/qlf#226]
In relation to PR#225:

 This is not obvious to me so please let me know which one is the case for QLF interface:

A- qlf is "flavour-agnostic" such that it does not care about missing jsons and alert_keys that are listed. In other words, it is OK to pile up all scalar metric names and all the pipeline steps that may or may not get executed on an exposure.  And QLF would work with the jsons that it finds in $QL_SPEC_REDUX/exposures/night/expid and the colouring of the petals would be determined from the alert_keys that are found in the existing jsons. Those steps_status that remain "None" , that would not affect the petal colour. 

B- qlf is not necessarily flavour agnostic; meaning that if I add a step called 'compute_fibflat' to the list of steps in  **self.steps_dic** that only gets executed on a flat exposure not on a science or an arc,  this addition would somehow mess with the interface setting.

I can explain more if it is not clear.

**Comment by sbailey** [comment]
There will be metrics that are specific to flavor, e.g. measuring fiber throughput from flats and measuring PSF sigmas from arcs, so at least at the level of detailed displays QLF cannot be flavor agnostic -- it needs to know the flavor in order to know what to display.

At the level of the overall pie charts, it could be flavor agnostic, just representing the success/warn/alert for any metrics that do exist.  I don't know how QLF is implemented in this regard.  @felipelm ?

@srheft please confirm that the wiki pages https://desi.lbl.gov/trac/wiki/Pipeline/QuickLook/QuicklookQAOutputs are up-to-date, or otherwise update as needed.

**Comment by Srheft** [comment]
* Wikipages and data model are updated.  

* My question was whether adding the two steps that only apply to flat and arc exposure to the self.steps_dic in scalar_metrics.py , would confuse the number of  pi-charts and crashes the interface.  But on a second thought, for the intermediate step that we are in, meaning before we migrate to the **CHECK_CCD, CHECK_FIBERS, CHECK_SPECTRA** mode, we can stick to the steps that work and apply to a science exposure [this PR] and pass other flavours through it as well. If the interface does not care that the new QA for flat and new QA for arc that now appear in the configuration file,  don't appear in scalar_metrics.py, then it's all OK. The only thing we are missing in this scenario is that the status keys of two flavour-specific QAs are not being included in deciding on the petal colours. But that will change in the next stage of QLF.

* The good news is that this issue goes away when we only have three pi-charts for CHECK_CCD, CHECK_FIBERS, CHECK_SPECTRA for all exposures. In this design, a flat exposure would have the fiber flat checks in CHECK_SPECTRA and an arc would have check resolution in CHECK_SPECTRA and a science exposure has all the ones currently in step 3+4.

Thoughts?

**Comment by sbailey** [comment]
@Srheft I don't know the details of how the code dictionaries will impact the pie charts, but please only do the minimal changes for getting the current QLF to work with the desihub/desispec#693 PR branch, and save the regrouping of the pie charts for a separate branch and PR.  i.e. ok if it doesn't show all of the QAs that you are now generating, but at least it should be able to run QL for arc, flat, science and have all the pie charts show up as green, for whatever QAs it does include.

I defer to @felipelm et al for any technical questions about the QLF code.  Thanks.

**Comment by Srheft** [comment]
@sbailey :  

* Current PR is just what you intended:

> it doesn't show all of the QAs that you are now generating, but at least it should be able to run QL for arc, flat, science and have all the pie charts show up as green, for whatever QAs it does include.

* All I wanted to mention is what you summarized: Two new flavour-specific QAs are not introduced to qlf in scalar_metrics.py  and that's hopefully OK. I was just asking if this is going to cause any issue.

**Comment by felipelm** [comment]
@Srheft @sbailey https://desi.lbl.gov/trac/wiki/Pipeline/QuickLook/QuicklookQAOutputs/Science doesn't seem to be up to date...

Steps are: `Initialization, Preprocessing, Spectral Extraction, Fiber Flattening and Sky Subtraction`
And should be according to QL_SummaryPages: `CHECK CCDs, CHECK FIBERS and CHECK SPECTRA`

Or am I looking in the wrong place?

**Comment by Srheft** [comment]
@felipelm: here is where I am confused too. Are we going to make that "pi chart name change" and "summary page" now or we wanted to see green petals for science frames first with the current setting and then migrate to the new "step name change" etc? 

I can totally change them right now. I thought that you are going to implement that change later. 

Also Initialization, Preprocessing, Spectral Extraction, Fiber Flattening and Sky Subtraction are still pipeline step names inside the code so the QAs in the wiki says. It is only in merged Jsons that the QAs  are categorized by the three CHECK_CCDs, CHECK_FIBERS and CHECK_SPECTRA  and we want the pi-charts [steps in qlf interface] to be also three and to also say  CHECK CCDs, CHECK FIBERS and CHECK SPECTRA

**Comment by Srheft** [comment]
@felipelm 
I just changed it to the way it is supposed to become at some point in the future. Please go teh changes if @sbailey is also ok to proceed. I may have misunderstood the point.(https://desi.lbl.gov/trac/wiki/Pipeline/QuickLook/QuicklookQAOutputs/Science)

**Comment by felipelm** [comment]
@Srheft @sbailey I created a [pull request](https://github.com/desihub/qlf/pull/229) with a proposed common ground to map keys generated by ql and used by qlf.

Let me know your thoughts.
