### ISSUE TITLE
yellow warnings in drill downs still appear as green check in obs history summary

### ISSUE THREAD

**Issue by sbailey** [desihub/qlf#264]
Testing http://desi-1.kpno.noao.edu:9090 using code from desispec #702 (now tag 0.25.0) and qlf #253, mostly looking at Observing History window and drill-downs.

arc exposure 3571 has green check, but when drilling down all 10 petals have yellow warnings for Step 1.

Other exposures have similar examples where drill downs have warnings that aren't propagated to the top level observing history check box.  If there is a warning/error down below, it should be flagged as a warning/error in the summary table.

**Comment by felipelm** [comment]
@sbailey please verify if this issue is fixed on http://desi-1.kpno.noao.edu:9090/observing-history

**Comment by sbailey** [comment]
@felipelm confirmed.  That looks good.  Thanks.
