### ISSUE TITLE
arc/flat COUNTBINS drill down broken

### ISSUE THREAD

**Issue by sbailey** [desihub/qlf#266]
Testing http://desi-1.kpno.noao.edu:9090 using code from desispec #702 (now tag 0.25.0) and qlf #253, mostly looking at Observing History window and drill-downs.

arc/flat exp 3571/3672 Step 2 COUNTBINS drill down "Missing RA and DEC"
(which is true because RA/DEC don't apply for arc/flat calibration exposures).
This does work for science exposures.  These plots could be done in x,y focal plane coordinates instead of RA,dec sky coordinates.

**Comment by felipelm** [comment]
@sbailey please verify if this issue is fixed on http://desi-1.kpno.noao.edu:9090

**Comment by sbailey** [comment]
It no longer shows an error (good) and includes the fiber status vs. fiber number (also good).  It would be even more helpful to also include the status vs. focal plane location like the science exposures, but plotted in x,y instead of ra,dec.  Some problems could be localized on the focal plane (thus the xy plot) and others could be localize on the CCD (thus the fiber number plot).  Feel free to close this and open a new ticket if you prefer, since the problem is no longer a bug where something is broken, but rather a new feature request now.

![image](https://user-images.githubusercontent.com/218471/47760023-94c1a780-dc6f-11e8-8d19-5db382d1ecc7.png)

**Comment by felipelm** [comment]
@sbailey no problem we will discuss this with the team and add it to the backlog.

@felipeaoli any thoughts before we close this?

**Comment by felipeaoli** [comment]
Thanks for the review @sbailey, I will include the xy plot. 

@felipelm If you agree, I  would to like to work in the suggested plot using a new branch.

**Comment by felipelm** [comment]
@felipeaoli ok let's do that just keep a reference to https://github.com/desihub/qlf/issues/266#issuecomment-434527296 on your PR please.
