### ISSUE TITLE
Naming inconsistencies

### ISSUE THREAD

**Issue by sbailey** [desihub/qlf#268]
Testing http://desi-1.kpno.noao.edu:9090 using code from desispec #702 (now tag 0.25.0) and qlf #253, mostly looking at Observing History window and drill-downs.

This is cosmetic, not a critical bug.

The observing history pie charts are labeled "Step 1", "Step 2", "Step 3", while the hover tooltips give the more useful "CHECK CCDS", "CHECK FIBERS", "CHECK SPECTRA".  It would be better to just label them with the "CHECK ABC" labels.

There are inconsistencies between what the metrics are called when hovering on the pie charts vs. what they are shown in the drill down.  In some cases the mapping is obvious (Bias AMP -> BIAS); in some cases they are semi-obvious ("Noise AMP" -> "RMS"), and in others they are derivable only by a process of elimination or expert knowledge (LITFRAC -> Countpix?  NGOODFIB -> COUNTBINS?).  Let's be consistent with how these are named.

**Comment by felipelm** [comment]
@sbailey please verify if this issue is fixed on http://desi-1.kpno.noao.edu:9090

**Comment by sbailey** [comment]
@felipelm Looks good, thanks.
